package agent

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

var (
	// ErrInvalidConfiguration identifies an invalid agent command or runner.
	ErrInvalidConfiguration = errors.New("invalid agent configuration")
	// ErrSetup identifies an I/O failure while preparing or finalizing an invocation.
	ErrSetup = errors.New("agent invocation setup failed")
	// ErrProcessStart identifies a process that could not be started.
	ErrProcessStart = errors.New("agent process failed to start")
	// ErrCanceled identifies an invocation stopped through context cancellation.
	ErrCanceled = errors.New("agent invocation canceled")
	// ErrNonZeroExit identifies a process that started and exited unsuccessfully.
	ErrNonZeroExit = errors.New("agent process exited non-zero")
)

// CommandRunner executes a validated agent command.
type CommandRunner struct {
	spec AgentCommand
}

// NewCommandRunner validates spec and returns a runner bound to an independent
// copy of it.
func NewCommandRunner(spec AgentCommand) (*CommandRunner, error) {
	if err := spec.Validate(); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidConfiguration, err)
	}

	spec.Args = append([]string(nil), spec.Args...)
	return &CommandRunner{spec: spec}, nil
}

// Run invokes the configured command using its selected prompt transport. It
// returns the path to a temporary file containing combined stdout and stderr.
func (r *CommandRunner) Run(ctx context.Context, prompt string) (string, error) {
	if r == nil {
		return "", fmt.Errorf("%w: command runner must not be nil", ErrInvalidConfiguration)
	}

	args := r.spec.Args
	sendPromptToStdin := false
	switch r.spec.PromptMode {
	case PromptModeStdin:
		sendPromptToStdin = true
	case PromptModeArg:
		args = append([]string(nil), r.spec.Args...)
		for i, arg := range args {
			if arg == promptPlaceholder {
				args[i] = prompt
				break
			}
		}
	default:
		return "", fmt.Errorf("%w: prompt mode %q execution is not implemented", ErrInvalidConfiguration, r.spec.PromptMode)
	}

	outFile, err := os.CreateTemp("", "gralph-agent-output-*.log")
	if err != nil {
		return "", fmt.Errorf("%w: could not create temp output file: %w", ErrSetup, err)
	}
	outPath := outFile.Name()

	cmd := exec.CommandContext(ctx, r.spec.Executable, args...) // #nosec G204 -- the executable and argument vector are explicit user configuration; no shell is involved
	if sendPromptToStdin {
		cmd.Stdin = strings.NewReader(prompt)
	}
	cmd.Stdout = outFile
	cmd.Stderr = outFile
	runErr := cmd.Run()
	if closeErr := outFile.Close(); closeErr != nil {
		_ = os.Remove(outPath) // #nosec G703 -- outPath is system-generated by os.CreateTemp
		return "", fmt.Errorf("%w: could not close temp output file: %w", ErrSetup, errors.Join(closeErr, runErr))
	}

	if runErr == nil {
		return outPath, nil
	}
	if ctxErr := ctx.Err(); ctxErr != nil {
		return outPath, fmt.Errorf("%w: %w", ErrCanceled, errors.Join(ctxErr, runErr))
	}
	if cmd.ProcessState == nil {
		return outPath, fmt.Errorf("%w: %w", ErrProcessStart, runErr)
	}
	return outPath, fmt.Errorf("%w: %w", ErrNonZeroExit, runErr)
}
