package agent

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// CommandRunner executes a validated agent command.
type CommandRunner struct {
	spec AgentCommand
}

// NewCommandRunner validates spec and returns a runner bound to an independent
// copy of it.
func NewCommandRunner(spec AgentCommand) (*CommandRunner, error) {
	if err := spec.Validate(); err != nil {
		return nil, fmt.Errorf("invalid agent command: %w", err)
	}

	spec.Args = append([]string(nil), spec.Args...)
	return &CommandRunner{spec: spec}, nil
}

// Run invokes the configured command with prompt as its standard input. It
// returns the path to a temporary file containing combined stdout and stderr.
func (r *CommandRunner) Run(ctx context.Context, prompt string) (string, error) {
	if r == nil {
		return "", fmt.Errorf("command runner must not be nil")
	}
	if r.spec.PromptMode != PromptModeStdin {
		return "", fmt.Errorf("prompt mode %q execution is not implemented", r.spec.PromptMode)
	}

	outFile, err := os.CreateTemp("", "gralph-agent-output-*.log")
	if err != nil {
		return "", fmt.Errorf("could not create temp output file: %w", err)
	}
	outPath := outFile.Name()

	cmd := exec.CommandContext(ctx, r.spec.Executable, r.spec.Args...) // #nosec G204 -- the executable and argument vector are explicit user configuration; no shell is involved
	cmd.Stdin = strings.NewReader(prompt)
	cmd.Stdout = outFile
	cmd.Stderr = outFile
	runErr := cmd.Run()
	if closeErr := outFile.Close(); closeErr != nil {
		_ = os.Remove(outPath) // #nosec G703 -- outPath is system-generated by os.CreateTemp
		return "", fmt.Errorf("could not close temp output file: %w", closeErr)
	}

	return outPath, runErr
}
