package agent

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

var (
	// ErrInvalidConfiguration identifies an invalid agent command or runner.
	ErrInvalidConfiguration = errors.New("invalid agent configuration")
	// ErrSetup identifies an I/O failure while preparing or finalizing an invocation.
	ErrSetup = errors.New("agent invocation setup failed")
	// ErrProcessStart identifies a process that could not be started.
	ErrProcessStart = errors.New("agent process failed to start")
	// ErrCanceled identifies an invocation stopped through context cancellation.
	ErrCanceled = errors.New("agent invocation canceled")
	// ErrNonZeroExit identifies a process that started and exited unsuccessfully.
	ErrNonZeroExit = errors.New("agent process exited non-zero")
)

// CommandRunner executes a validated agent command.
type CommandRunner struct {
	spec AgentCommand
}

// CommandOutput identifies the separately captured streams from one command.
// Stream interleaving is not recorded. Call Cleanup after consuming the files,
// including when Run returns an error.
type CommandOutput struct {
	StdoutPath string
	StderrPath string
}

// Cleanup removes both captured stream files. It is safe to call more than once.
func (o CommandOutput) Cleanup() error {
	return errors.Join(removeOutputFile(o.StdoutPath), removeOutputFile(o.StderrPath))
}

func removeOutputFile(path string) error {
	if path == "" {
		return nil
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) { // #nosec G703 -- paths are generated by os.CreateTemp
		return err
	}
	return nil
}

// NewCommandRunner validates spec and returns a runner bound to an independent
// copy of it.
func NewCommandRunner(spec AgentCommand) (*CommandRunner, error) {
	if err := spec.Validate(); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidConfiguration, err)
	}

	spec.Args = append([]string(nil), spec.Args...)
	return &CommandRunner{spec: spec}, nil
}

// Run invokes the configured command using its selected prompt transport. It
// returns separate temporary files for stdout and stderr. The caller owns the
// returned files and must call CommandOutput.Cleanup on every outcome.
func (r *CommandRunner) Run(ctx context.Context, prompt string) (CommandOutput, error) {
	if r == nil {
		return CommandOutput{}, fmt.Errorf("%w: command runner must not be nil", ErrInvalidConfiguration)
	}

	args := r.spec.Args
	sendPromptToStdin := false
	switch r.spec.PromptMode {
	case PromptModeStdin:
		sendPromptToStdin = true
	case PromptModeArg:
		args = append([]string(nil), r.spec.Args...)
		for i, arg := range args {
			if arg == promptPlaceholder {
				args[i] = prompt
				break
			}
		}
	default:
		return CommandOutput{}, fmt.Errorf("%w: prompt mode %q execution is not implemented", ErrInvalidConfiguration, r.spec.PromptMode)
	}

	stdoutFile, err := os.CreateTemp("", "gralph-agent-stdout-*.log")
	if err != nil {
		return CommandOutput{}, fmt.Errorf("%w: could not create stdout capture: %w", ErrSetup, err)
	}
	capture := CommandOutput{StdoutPath: stdoutFile.Name()}
	stderrFile, err := os.CreateTemp("", "gralph-agent-stderr-*.log")
	if err != nil {
		closeErr := stdoutFile.Close()
		cleanupErr := capture.Cleanup()
		return CommandOutput{}, fmt.Errorf("%w: could not create stderr capture: %w", ErrSetup, errors.Join(err, closeErr, cleanupErr))
	}
	capture.StderrPath = stderrFile.Name()

	cmd := exec.CommandContext(ctx, r.spec.Executable, args...) // #nosec G204 -- the executable and argument vector are explicit user configuration; no shell is involved
	configureProcessTree(cmd)
	if sendPromptToStdin {
		cmd.Stdin = strings.NewReader(prompt)
	}
	cmd.Stdout = stdoutFile
	cmd.Stderr = stderrFile
	runErr := cmd.Run()
	if closeErr := errors.Join(stdoutFile.Close(), stderrFile.Close()); closeErr != nil {
		cleanupErr := capture.Cleanup()
		return CommandOutput{}, fmt.Errorf("%w: could not close stream capture: %w", ErrSetup, errors.Join(closeErr, runErr, cleanupErr))
	}

	if runErr == nil {
		return capture, nil
	}
	if ctxErr := ctx.Err(); ctxErr != nil {
		return capture, fmt.Errorf("%w: %w", ErrCanceled, errors.Join(ctxErr, runErr))
	}
	if cmd.ProcessState == nil {
		return capture, fmt.Errorf("%w: %w", ErrProcessStart, runErr)
	}
	return capture, fmt.Errorf("%w: %w", ErrNonZeroExit, runErr)
}
